//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Chat = _ModuleRegistry.module("Chat");

    Chat.Message = class
    {
        constructor(sender = "", content = "", timestamp = "", type = "")
        {
            this.sender = sender;
            this.content = content;
            this.timestamp = timestamp;
            this.type = type;
        }

        _write(ostr)
        {
            ostr.writeString(this.sender);
            ostr.writeString(this.content);
            ostr.writeString(this.timestamp);
            ostr.writeString(this.type);
        }

        _read(istr)
        {
            this.sender = istr.readString();
            this.content = istr.readString();
            this.timestamp = istr.readString();
            this.type = istr.readString();
        }

        static get minWireSize()
        {
            return  4;
        }
    };

    Slice.defineStruct(Chat.Message, true, true);

    Slice.defineSequence(Chat, "MessageSeqHelper", "Chat.Message", false);

    Slice.defineSequence(Chat, "StringSeqHelper", "Ice.StringHelper", false);

    Slice.defineSequence(Chat, "AudioDataHelper", "Ice.ByteHelper", true);

    const iceC_Chat_ChatCallback_ids = [
        "::Chat::ChatCallback",
        "::Ice::Object"
    ];

    Chat.ChatCallback = class extends Ice.Object
    {
    };

    Chat.ChatCallbackPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ChatCallback, Chat.ChatCallbackPrx, iceC_Chat_ChatCallback_ids, 0,
    {
        "onMessageReceived": [, , , , , [[Chat.Message]], , , , ],
        "onUserJoined": [, , , , , [[7]], , , , ],
        "onUserLeft": [, , , , , [[7]], , , , ],
        "onGroupCreated": [, , , , , [[7], [7]], , , , ],
        "onAudioReceived": [, , , , , [[7], ["Chat.AudioDataHelper"], [7]], , , , ],
        "onCallRequest": [, , , , , [[7], [7]], , , , ],
        "onCallAccepted": [, , , , , [[7], [7]], , , , ],
        "onCallRejected": [, , , , , [[7]], , , , ],
        "onCallEnded": [, , , , , [[7]], , , , ],
        "onGroupCallRequest": [, , , , , [[7], [7], [7]], , , , ],
        "onGroupCallStarted": [, , , , , [[7], [7]], , , , ],
        "onGroupCallEnded": [, , , , , [[7]], , , , ],
        "onCallAudioStream": [, , , , , [[7], ["Chat.AudioDataHelper"]], , , , ]
    });

    const iceC_Chat_ChatService_ids = [
        "::Chat::ChatService",
        "::Ice::Object"
    ];

    Chat.ChatService = class extends Ice.Object
    {
    };

    Chat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ChatService, Chat.ChatServicePrx, iceC_Chat_ChatService_ids, 0,
    {
        "registerUser": [, , , , [1], [[7], ["Chat.ChatCallbackPrx"]], , , , ],
        "unregisterUser": [, , , , , [[7]], , , , ],
        "listUsers": [, , , , ["Chat.StringSeqHelper"], , , , , ],
        "sendPrivateMessage": [, , , , [1], [[7], [7], [7]], , , , ],
        "getPrivateHistory": [, , , , ["Chat.MessageSeqHelper"], [[7], [7]], , , , ],
        "createGroup": [, , , , [1], [[7], [7]], , , , ],
        "addUserToGroup": [, , , , [1], [[7], [7]], , , , ],
        "sendGroupMessage": [, , , , [1], [[7], [7], [7]], , , , ],
        "getGroupHistory": [, , , , ["Chat.MessageSeqHelper"], [[7]], , , , ],
        "listMyGroups": [, , , , ["Chat.StringSeqHelper"], [[7]], , , , ],
        "sendAudioMessage": [, , , , [1], [[7], [7], ["Chat.AudioDataHelper"], [7]], , , , ],
        "sendGroupAudioMessage": [, , , , [1], [[7], [7], ["Chat.AudioDataHelper"], [7]], , , , ],
        "initiateCall": [, , , , [1], [[7], [7], [7]], , , , ],
        "acceptCall": [, , , , [1], [[7], [7], [7]], , , , ],
        "rejectCall": [, , , , [1], [[7], [7]], , , , ],
        "endCall": [, , , , [1], [[7], [7]], , , , ],
        "initiateGroupCall": [, , , , [1], [[7], [7], [7]], , , , ],
        "joinGroupCall": [, , , , [1], [[7], [7], [7]], , , , ],
        "leaveGroupCall": [, , , , [1], [[7], [7], [7]], , , , ],
        "endGroupCall": [, , , , [1], [[7], [7]], , , , ],
        "streamCallAudio": [, , , , [1], [[7], [7], ["Chat.AudioDataHelper"]], , , , ],
        "streamGroupCallAudio": [, , , , [1], [[7], [7], ["Chat.AudioDataHelper"]], , , , ]
    });
    exports.Chat = Chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
